name: Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  FORCE_COLOR: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Build web
      #   run: pnpm buildWebStandalone

      - name: Build
        run: pnpm build --standalone

      - name: Clean up obsolete files
        run: |
          rm -rf dist/*-unpacked dist/monaco Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DevBuild-Artifacts
          path: dist/
